// 获取网站信息
const GET_WEBINFO = 'GET_WEBINFO'
// 获取文章
const GET_ARTICLE = 'GET_ARTICLE'
// 获取热门文章
const GET_HOTARTICLE = 'GET_HOTARTICLE'
// 获取文章详情
const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'
// 获取文章评论
const GET_ARTICLE_COMMENT = 'GET_ARTICLE_COMMENT'
// 获取标签
const GET_TAGS = 'GET_TAGS'
// 获取搜索信息
const GET_SEARCH_ARTICLE = 'GET_SEARCH_ARTICLE'

export default{
	GET_WEBINFO,
	GET_ARTICLE,
	GET_HOTARTICLE,
	GET_ARTICLE_DETAIL,
	GET_ARTICLE_COMMENT,
	GET_TAGS,
	GET_SEARCH_ARTICLE
}