// 获取网站信息
const GET_WEBINFO = 'GET_WEBINFO'
// 获取文章
const GET_ARTICLE = 'GET_ARTICLE'
// 获取热门文章
const GET_HOTARTICLE = 'GET_HOTARTICLE'
// 获取文章详情
const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'
// 获取文章评论
const GET_ARTICLE_COMMENT = 'GET_ARTICLE_COMMENT'

export default{
	GET_WEBINFO,
	GET_ARTICLE,
	GET_HOTARTICLE,
	GET_ARTICLE_DETAIL,
	GET_ARTICLE_COMMENT
}